import { NextRequest, NextResponse } from 'next/server';

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const apiUrl = searchParams.get('apiUrl') ?? 'https://your-dep-analyzer.vercel.app';
  const maxScore = searchParams.get('maxScore') ?? '70';
  const ecosystem = searchParams.get('ecosystem') ?? 'npm';
  const manifestFile = searchParams.get('manifest') ?? 'package.json';

  const yaml = `# Dependency Risk Analysis — generated by dep-analyzer
# Place this file at .github/workflows/dep-analyzer.yml

name: Dependency Risk Check

on:
  push:
    paths:
      - '${manifestFile}'
      - 'package-lock.json'
      - 'yarn.lock'
  pull_request:
    paths:
      - '${manifestFile}'

jobs:
  dep-risk:
    name: Analyze Dependency Risk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read manifest
        id: manifest
        run: |
          CONTENT=$(cat ${manifestFile} | jq -Rs .)
          echo "raw=$CONTENT" >> $GITHUB_OUTPUT

      - name: Analyze dependencies
        id: analysis
        run: |
          RESPONSE=$(curl -s -X POST \\
            -H "Content-Type: application/json" \\
            -d "{\\\"raw\\\": $(cat ${manifestFile} | jq -Rs .), \\\"ecosystem\\\": \\\"${ecosystem}\\\"}" \\
            ${apiUrl}/api/analyze)

          echo "response=$RESPONSE" >> $GITHUB_OUTPUT

          SCORE=$(echo "$RESPONSE" | jq '.overallScore // 0')
          CRITICAL=$(echo "$RESPONSE" | jq '.criticalCount // 0')
          HIGH=$(echo "$RESPONSE" | jq '.highCount // 0')

          echo "score=$SCORE" >> $GITHUB_OUTPUT
          echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
          echo "high=$HIGH" >> $GITHUB_OUTPUT

      - name: Print summary
        run: |
          echo "## Dependency Risk Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Overall Score | \${{ steps.analysis.outputs.score }}/100 |" >> $GITHUB_STEP_SUMMARY
          echo "| Critical | \${{ steps.analysis.outputs.critical }} |" >> $GITHUB_STEP_SUMMARY
          echo "| High | \${{ steps.analysis.outputs.high }} |" >> $GITHUB_STEP_SUMMARY

      - name: Fail on policy violation
        run: |
          SCORE=\${{ steps.analysis.outputs.score }}
          if [ "$SCORE" -gt "${maxScore}" ]; then
            echo "::error::Dependency risk score $SCORE exceeds maximum allowed score of ${maxScore}"
            exit 1
          fi
          echo "::notice::Dependency risk score $SCORE is within allowed threshold of ${maxScore}"
`;

  return new NextResponse(yaml, {
    headers: {
      'Content-Type': 'text/yaml',
      'Content-Disposition': 'attachment; filename="dep-analyzer.yml"',
    },
  });
}
